analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    unnecessary_import: ignore
    unused_import: ignore
    unused_local_variable: ignore
    dead_null_aware_expression: ignore
    unnecessary_null_comparison: ignore
    unnecessary_non_null_assertion: ignore
    parse_error: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.drift.dart"
    - "**/*.drift.g.part"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "**/.dart_tool/**"
    - "**/build/**"

linter:
  rules: false
