targets:
  $default:
    builders:
      drift_dev:
        include:
          - "**/tables.dart"
          - "**/app_database.dart"
          - "**/skin_table.dart"
        options:
          write_from_json_string_constructor: true
      freezed:
        include:
          - "**/skin_definitions.dart"
          - "**/mission_models.dart"
